### ISSUE TITLE
Server.py doesnt show correct ip. 

### ISSUE THREAD

**Issue by r00t4rd3d** [benmoose39/ustvgo_to_m3u#7] opened 2021-12-11 10:06 UTC
When I run "python3 server.py" it says its running but on ip 0.0.0.0 and I think its related to this code:

 app.run('0.0.0.0', PORT)

It displays the right port but only 0's for ip.

**Comment by Theitfixer85** [comment] 2021-12-11 12:03
> When I run "python3 server.py" it says its running but on ip 0.0.0.0 and I think its related to this code:
> 
> app.run('0.0.0.0', PORT)
> 
> It displays the right port but only 0's for ip.

Just tested and works fine

Open sever.py

Change the 10.10.10.10 to your device ip but make sure you leave the quotes either side! 
SERVER_IP = '10.10.10.10'   # Edit this line

Eg 
SERVER_IP = '192.168.1.123'   # Edit this line

**Comment by r00t4rd3d** [comment] 2021-12-12 13:11
This is a visual bug only!

The server works just fine. After I start it, it just displays the wrong ip in the terminal, check my photo. What ever you change 10.10.10.10 to or if you just leave it at that, it still reports 0.0.0.0 in the terminal after you run it. The code app.run('0.0.0.0', PORT) is wrong. Its going to display 0.0.0.0 as the ip no matter what you change the ip to in the script. I am no coder but I think it should be something like "app.run(IP,PORT)" If you change 10.10.10.10 to 192.168.0.10 and change app.run('192.168.0.10', PORT) I think the right ip would be displayed but I have not tried it. 

![IMG_20211212_080001986](https://user-images.githubusercontent.com/3196633/145713443-f02ca429-3596-4164-88d5-bc20f60c3aea.jpg)

**Comment by benmoose39** [comment] 2021-12-12 13:16
This is not a bug.
0.0.0.0 just means that the server is running on all the interfaces. That includes all the ip addresses which are assigned to the machine- including loopback address and vpn services, if any.

**Comment by Theitfixer85** [comment] 2021-12-12 13:16
> This is a visual bug only!
> 
> The server works just fine. After I start it, it just displays the wrong ip in the terminal, check my photo. What ever you change 10.10.10.10 to or if you just leave it at that, it still reports 0.0.0.0 in the terminal after you run it. The code app.run('0.0.0.0', PORT) is wrong I think. Its going to display 0.0.0.0 as the ip no matter what you change the ip to in the script. I am no coder but I think it should be something like "app.run(IP,PORT)" If you change 10.10.10.10 to 192.168.0.10 and change app.run('192.168.0.10', PORT) I think the right ip would be displayed but I have not tried it.
> 
> ![IMG_20211212_080001986](https://user-images.githubusercontent.com/3196633/145713443-f02ca429-3596-4164-88d5-bc20f60c3aea.jpg)

It's not a bug - it works fine displaying the correct information. Did you include your ip with the quotes as stated in my previous reply?

Works fine for me - make sure you the latest python and flask installed

![Screenshot_2021-12-12-13-13-17-907_com termux_1](https://user-images.githubusercontent.com/11890010/145713844-f8c42f31-b893-4987-ad1d-c30fdd76d918.jpg)

**Closed** 2021-12-12 13:25 UTC
